######################################################################
# Automatically generated by qmake (2.01a) mar. oct. 6 18:00:52 2015
######################################################################

QT += testlib
TEMPLATE = app
TARGET = Test
DEPENDPATH += . instructions Tests
INCLUDEPATH += . instructions Tests

# Input
HEADERS += instructions/AInstructionModel.hpp \
           instructions/InstructionFactoryUtils.hpp \
           Tests/TestAInstructionModel.hpp \
           Tests/TestInstructionFactoryUtils.hpp
SOURCES += instructions/AInstructionModel.cpp \
           instructions/InstructionFactoryUtils.cpp \
           Tests/TestAInstructionModel.cpp \
           Tests/TestInstructionFactoryUtils.cpp
