######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 26 00:58:20 2015
######################################################################

TEMPLATE = app

TARGET = TestInstructionDisconnect

QT -= gui
QT += testlib

CONFIG -= app_bundle
CONFIG += console

QMAKE_CXXFLAGS += -std=c++11

INCLUDEPATH += . \
               ../../common/microkernel_architecture/microkernel_modules/instructions \
               ../../common/microkernel_architecture/microkernel_modules/instructions/messages_network/ \
               ../../common/others/

# Input
HEADERS += TestInstructionDisconnect.hpp \
           ../../common/microkernel_architecture/microkernel_modules/instructions/AInstruction.hpp \
           ../../common/microkernel_architecture/microkernel_modules/instructions/InstructionBuffer.hpp \
           ../../common/microkernel_architecture/microkernel_modules/instructions/AInstructionParameter.hpp \
           ../../common/microkernel_architecture/microkernel_modules/instructions/AInstructionBusClient.hpp \
           ../../common/microkernel_architecture/microkernel_modules/instructions/messages_network/Disconnect.hpp

SOURCES += TestInstructionDisconnect.cpp \
           ../../common/microkernel_architecture/microkernel_modules/instructions/AInstruction.cpp \
           ../../common/microkernel_architecture/microkernel_modules/instructions/InstructionBuffer.cpp \
           ../../common/microkernel_architecture/microkernel_modules/instructions/AInstructionParameter.cpp \
           ../../common/microkernel_architecture/microkernel_modules/instructions/AInstructionBusClient.cpp \
           ../../common/microkernel_architecture/microkernel_modules/instructions/messages_network/Disconnect.cpp
