######################################################################
# Automatically generated by qmake (3.0) jeu. oct. 1 06:24:07 2015
######################################################################

QT += testlib
TEMPLATE = app
TARGET = TestFileObjectToTest
INCLUDEPATH += .

# Input
HEADERS += ../../FileObject.hpp
SOURCES += TestFileObjectToTest.cpp ../../FileObject.cpp
