######################################################################
# Automatically generated by qmake (3.0) jeu. oct. 1 06:26:43 2015
######################################################################

QT += testlib
TEMPLATE = app
TARGET = TestFileManagerUtilsToTest
INCLUDEPATH += .

# Input
HEADERS += ../../FileManagerUtils.hpp
SOURCES += TestFileManagerUtilsToTest.cpp ../../FileManagerUtils.cpp
