######################################################################
# Automatically generated by qmake (3.0) Mon Jan 11 07:47:31 2016
######################################################################

TARGET = TestEasyLogging++

DEFINES += SRCDIR=\\\"$$PWD/\\\"

TEMPLATE = app

QT += \
   testlib

CONFIG -= app_bundle
CONFIG += \
       console \
       c++11

COMMON_ALL = $${PWD}/../../common

INCLUDEPATH += \
            $${COMMON_ALL}/log/src

HEADERS += \
        $${COMMON_ALL}/log/src/easylogging++.h

# Input
SOURCES += main.cpp
