######################################################################
# Automatically generated by qmake (3.0) jeu. oct. 15 08:53:34 2015
######################################################################

TEMPLATE = app
TARGET = functionalities
INCLUDEPATH += .

# Input
HEADERS += AFunctionality.hpp FunctionalitiesManager.hpp
SOURCES += AFunctionality.cpp FunctionalitiesManager.cpp main.cpp
