######################################################################
# Automatically generated by qmake (3.0) ven. oct. 16 09:54:41 2015
######################################################################

TEMPLATE = app
TARGET = functionalities
INCLUDEPATH += .

# Input
HEADERS += AFunctionality.hpp FunctionalitiesManager.hpp MainController.hpp
SOURCES += AFunctionality.cpp \
           FunctionalitiesManager.cpp \
           main.cpp \
           MainController.cpp
