######################################################################
# Automatically generated by qmake (3.0) mar. sept. 15 15:35:54 2015
######################################################################

TEMPLATE = app
TARGET = common
INCLUDEPATH += .

# Input
HEADERS += INetworkClientManager.hpp NetworkClientManager.hpp AInstructionModel.hpp
SOURCES += NetworkClientManager.cpp AInstructionModel.cpp
QT += network
QT += widgets
