######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 26 02:40:35 2015
######################################################################

TEMPLATE = app

TARGET = TestInstructionGetAllUsersRights

QT -= gui
QT += testlib

CONFIG -= app_bundle
CONFIG += console

QMAKE_CXXFLAGS += -std=c++11

INCLUDEPATH += . \
               ../../common/microkernel_architecture/microkernel_modules/instructions \
               ../../common/microkernel_architecture/microkernel_modules/instructions/messages_network/ \
               ../../common/others/

# Input
HEADERS += TestInstructionGetAllUsersRights.hpp \
           ../../common/microkernel_architecture/microkernel_modules/instructions/AInstruction.hpp \
           ../../common/microkernel_architecture/microkernel_modules/instructions/InstructionBuffer.hpp \
           ../../common/microkernel_architecture/microkernel_modules/instructions/AInstructionParameter.hpp \
           ../../common/microkernel_architecture/microkernel_modules/instructions/AInstructionBusClient.hpp \
           ../../common/microkernel_architecture/microkernel_modules/instructions/messages_network/GetAllUsersRights.hpp

SOURCES += TestInstructionGetAllUsersRights.cpp \
           ../../common/microkernel_architecture/microkernel_modules/instructions/AInstruction.cpp \
           ../../common/microkernel_architecture/microkernel_modules/instructions/InstructionBuffer.cpp \
           ../../common/microkernel_architecture/microkernel_modules/instructions/AInstructionParameter.cpp \
           ../../common/microkernel_architecture/microkernel_modules/instructions/AInstructionBusClient.cpp \
           ../../common/microkernel_architecture/microkernel_modules/instructions/messages_network/GetAllUsersRights.cpp
