######################################################################
# Automatically generated by qmake (3.0) lun. oct. 5 11:47:33 2015
######################################################################

QT += testlib
TEMPLATE = app
TARGET = ANetworkInstruction
INCLUDEPATH += . ../../instructions

# Input
HEADERS += TestANetworkInstruction.hpp
SOURCES += TestANetworkInstruction.cpp ../../instructions/ANetworkInstruction.cpp ../../instructions/AInstructionModel.cpp
