######################################################################
# Automatically generated by qmake (3.0) sam. oct. 31 03:41:00 2015
######################################################################

TEMPLATE = app
TARGET = TestFileManagerUtils
INCLUDEPATH += . ../../common/microkernel_architecture/microkernel_modules/file_manager/
QT += testlib

# Input
HEADERS += TestFileManagerUtils.hpp ../../common/microkernel_architecture/microkernel_modules/file_manager/FileManagerUtils.hpp
SOURCES += TestFileManagerUtils.cpp ../../common/microkernel_architecture/microkernel_modules/file_manager/FileManagerUtils.cpp
