######################################################################
# Automatically generated by qmake (3.0) dim. nov. 22 18:54:31 2015
######################################################################

TEMPLATE = app

DEFINES += SRCDIR=\\\"$$PWD/\\\"

QT       -= gui
QT       += testlib

CONFIG   -= app_bundle
CONFIG   += console \
            c++11

TARGET = TestAFunctionality

COMMON_ALL = $${PWD}/../../common

INCLUDEPATH += \
	. \
	$${COMMON_ALL}/others \
	$${COMMON_ALL}/microkernel_architecture/microkernel_modules/instructions
	$${COMMON_ALL}/microkernel_architecture/microkernel_modules/functionalities

# Input
HEADERS += \
	BasicAFunctionality.hpp \
	TestAFunctionality.hpp \
    $${COMMON_ALL}/others/struct_packed.h \
    $${COMMON_ALL}/microkernel_architecture/microkernel_modules/instructions/AInstruction.hpp \
    $${COMMON_ALL}/microkernel_architecture/microkernel_modules/instructions/AInstructionParameter.hpp \
    $${COMMON_ALL}/microkernel_architecture/microkernel_modules/functionalities/BasicAFunctionality.hpp \
    $${COMMON_ALL}/microkernel_architecture/microkernel_modules/functionalities/TestAFunctionality.hpp

SOURCES += \
	BasicAfunctionality.cpp \
	TestAFunctionality.cpp \
    $${COMMON_ALL}/microkernel_architecture/microkernel_modules/instructions/AInstruction.cpp \
    $${COMMON_ALL}/microkernel_architecture/microkernel_modules/instructions/AInstructionParameter.cpp \
    $${COMMON_ALL}/microkernel_architecture/microkernel_modules/functionalities/BasicAFunctionality.cpp \
    $${COMMON_ALL}/microkernel_architecture/microkernel_modules/functionalities/TestAFunctionality.cpp