######################################################################
# Automatically generated by qmake (3.0) jeu. oct. 1 14:48:38 2015
######################################################################

QT += testlib
TEMPLATE = app
TARGET = Tests
INCLUDEPATH += .

# Input
HEADERS += TestAInstructionModel.hpp
SOURCES += TestAInstructionModel.cpp
