######################################################################
# Automatically generated by qmake (3.0) lun. sept. 28 17:14:45 2015
######################################################################

QT += testlib
TEMPLATE = app
TARGET = Tests
INCLUDEPATH += .

# Input
HEADERS += ../FileManagerUtils.hpp
SOURCES += TestFileManagerUtils.cpp ../FileManagerUtils.cpp
