######################################################################
# Automatically generated by qmake (3.0) jeu. oct. 1 11:14:08 2015
######################################################################

QT += testlib
TEMPLATE = app
TARGET = UnitTests
INCLUDEPATH += ./ ../

# Input
HEADERS += TestAInstructionModel.hpp
SOURCES += TestAInstructionModel.cpp ../AInstructionModel.cpp
