######################################################################
# Automatically generated by qmake (3.0) lun. oct. 26 19:18:41 2015
######################################################################

TEMPLATE = app
TARGET = database_manager
INCLUDEPATH += .
INCLUDEPATH += /usr/include/mysql

# Input
HEADERS += Entity.hpp
SOURCES += Entity.cpp main.cpp
QT += sql
QT+=widgets
