######################################################################
# Automatically generated by qmake (3.0) mar. sept. 15 15:35:54 2015
######################################################################

TEMPLATE = app
TARGET = common
INCLUDEPATH += . ../../../../common

# Input
HEADERS += INetworkClientManager.hpp NetworkClientManager.hpp ../../../../common/AInstructionModel.hpp
SOURCES += NetworkClientManager.cpp ../../../../common/AInstructionModel.cpp
QT += network
QT += widgets
