######################################################################
# Automatically generated by qmake (3.0) lun. oct. 5 11:47:33 2015
######################################################################

QT += testlib
TEMPLATE = app
TARGET = ANetworkInstruction
INCLUDEPATH += . ../../common/microkernel_architecture/microkernel_modules/instructions

# Input
HEADERS += TestANetworkInstruction.hpp
SOURCES += TestANetworkInstruction.cpp
SOURCES += ../../common/microkernel_architecture/microkernel_modules/instructions/ANetworkInstruction.cpp
SOURCES += ../../common/microkernel_architecture/microkernel_modules/instructions/AInstructionModel.cpp
