######################################################################
# Automatically generated by qmake (2.01a) mar. oct. 6 18:16:57 2015
######################################################################

QT += testlib
TEMPLATE = app
TARGET = Tests
DEPENDPATH += ../../microkernel ../instructions .
INCLUDEPATH += . ../instructions

# Input
HEADERS += ../instructions/AInstructionModel.hpp \
           ../instructions/InstructionFactory.hpp \
           TestAInstructionModel.hpp \
           TestInstructionFactory.hpp
SOURCES += ../instructions/AInstructionModel.cpp \
           ../instructions/InstructionFactory.cpp \
           TestAInstructionModel.cpp \
           TestInstructionFactory.cpp
