######################################################################
# Automatically generated by qmake (2.01a) mar. oct. 6 13:08:15 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += TestAInstructionModel.hpp TestInstructionFactoryUtils.hpp
SOURCES += TestAInstructionModel.cpp TestInstructionFactoryUtils.cpp
