######################################################################
# Automatically generated by qmake (2.01a) mar. oct. 6 18:16:57 2015
######################################################################

TARGET = TestInstructionFactory

TEMPLATE = app

CONFIG   -= app_bundle
CONFIG   += console c++11

QT       -= gui
QT       += testlib

INCLUDEPATH += \
    ../../common/microkernel_architecture/microkernel_modules/instructions

HEADERS += \
    ../../common/microkernel_architecture/microkernel_modules/instructions/AInstructionModel.hpp \
    ../../common/microkernel_architecture/microkernel_modules/instructions/ANetworkInstruction.hpp \
    ../../common/microkernel_architecture/microkernel_modules/instructions/InstructionFactory.hpp \
    TestInstructionFactory.hpp

SOURCES += \
    ../../common/microkernel_architecture/microkernel_modules/instructions/ANetworkInstruction.cpp \
    ../../common/microkernel_architecture/microkernel_modules/instructions/AInstructionModel.cpp \
    ../../common/microkernel_architecture/microkernel_modules/instructions/InstructionFactory.cpp \
    TestInstructionFactory.cpp
